import eventDescription from '../formData/eventDescription.json' with { type: 'json' }

type FieldDescriptor = {
  id: string
  type: string
  options?: string[]
  nameFields?: string[]
  streetAddressFields?: { id: string; type: string; addressType: 'DOMESTIC' | 'INTERNATIONAL' }[]
}

const TYPE_MAP: Record<string, string> = {
  TEXT: 'string',
  TEXTAREA: 'string',
  NUMBER: 'number',
  DATE: 'CrvsDate',
  TIME: 'string',
  EMAIL: 'string',
  PHONE: 'string',
  ID: 'string',
  CHECKBOX: 'boolean',
  AGE: 'number',
  COUNTRY: 'Country',
  FACILITY: 'Facility',
  ADDRESS: 'Address',
  NAME: 'Name'
}

const IMPORTED_TYPES: Record<string, string> = {
  CrvsDate: './staticTypes.ts',
  Country: './staticTypes.ts',
  Facility: './staticTypes.ts',
  Address: './sharedTypes_generated.ts',
  Name: './sharedTypes_generated.ts'
}

function toCamelCase(id: string): string {
  return id.replace(/[.\-](\w)/g, (_: string, c: string) => c.toUpperCase())
}

function toTypeName(id: string): string {
  const camel = toCamelCase(id)
  return camel.charAt(0).toUpperCase() + camel.slice(1)
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function generateSharedTypes(description: Record<string, FieldDescriptor[]>): void {
  const allNameFields = new Set<string>()
  const domesticFields: { id: string }[] = []
  const internationalFields: { id: string }[] = []
  const seenDomesticIds = new Set<string>()
  const seenInternationalIds = new Set<string>()

  for (const fields of Object.values(description)) {
    for (const field of fields) {
      if (field.type === 'NAME' && field.nameFields) {
        field.nameFields.forEach((f) => allNameFields.add(f))
      }
      if (field.type === 'ADDRESS' && field.streetAddressFields) {
        for (const sf of field.streetAddressFields) {
          if (sf.addressType === 'DOMESTIC' && !seenDomesticIds.has(sf.id)) {
            seenDomesticIds.add(sf.id)
            domesticFields.push({ id: sf.id })
          } else if (sf.addressType === 'INTERNATIONAL' && !seenInternationalIds.has(sf.id)) {
            seenInternationalIds.add(sf.id)
            internationalFields.push({ id: sf.id })
          }
        }
      }
    }
  }

  const lines = [
    '// This file is auto-generated by typeGenerator.ts. Do not edit manually.',
    `import type { AdminStructure, Country } from './staticTypes.ts'`,
    '',
    'export type Name = {',
    ...[...allNameFields].map((f) => `  ${f}?: string`),
    '}',
    '',
    'export type DomesticAddress = {',
    `  addressType: 'DOMESTIC'`,
    '  country: Country',
    '  administrativeArea?: AdminStructure',
    '  streetLevelDetails: {',
    ...domesticFields.map((sf) => `    ${sf.id}?: string`),
    '  }',
    '}',
    '',
    'export type InternationalAddress = {',
    `  addressType: 'INTERNATIONAL'`,
    '  country: Country',
    '  administrativeArea?: AdminStructure',
    '  streetLevelDetails: {',
    ...internationalFields.map((sf) => `    ${sf.id}?: string`),
    '  }',
    '}',
    '',
    'export type Address = DomesticAddress | InternationalAddress',
    ''
  ]

  const outputPath = new URL('../types/sharedTypes_generated.ts', import.meta.url)
  Deno.writeTextFileSync(outputPath, lines.join('\n'))
  console.log(`Written: ${outputPath.pathname}`)
}

export function generateTypes(
  description: Record<string, FieldDescriptor[]> = eventDescription as Record<string, FieldDescriptor[]>
): void {
  generateSharedTypes(description)

  for (const [eventName, fields] of Object.entries(description)) {
    const typeLines: string[] = []
    const fieldLines: string[] = []
    const usedImports: Set<string> = new Set()

    for (const field of fields) {
      if (field.type === 'SELECT' || field.type === 'RADIO_GROUP') {
        const typeName = toTypeName(field.id)
        const union =
          field.options && field.options.length > 0
            ? field.options.map((o) => `'${o}'`).join(' | ')
            : 'string'
        typeLines.push(`export type ${typeName} = ${union}`)
        fieldLines.push(`  '${field.id}'?: ${typeName}`)
      } else {
        const tsType = TYPE_MAP[field.type] ?? 'unknown'
        if (tsType in IMPORTED_TYPES) usedImports.add(tsType)
        fieldLines.push(`  '${field.id}'?: ${tsType}`)
      }
    }

    const lines: string[] = [
      `// This file is auto-generated by typeGenerator.ts. Do not edit manually.`
    ]

    const importsBySource = new Map<string, string[]>()
    for (const typeName of usedImports) {
      const source = IMPORTED_TYPES[typeName]
      if (!importsBySource.has(source)) importsBySource.set(source, [])
      importsBySource.get(source)!.push(typeName)
    }
    for (const [source, typeNames] of [...importsBySource].sort()) {
      lines.push(
        `import type { ${typeNames.sort().join(', ')} } from '${source}'`
      )
    }

    lines.push('')
    lines.push(...typeLines)

    if (typeLines.length > 0) lines.push('')

    const interfaceName = `${capitalize(toCamelCase(eventName))}Fields`
    lines.push(`export interface ${interfaceName} {`)
    lines.push(...fieldLines)
    lines.push('}')
    lines.push('')

    const outputPath = new URL(
      `../types/${toCamelCase(eventName)}Types_generated.ts`,
      import.meta.url
    )
    Deno.writeTextFileSync(outputPath, lines.join('\n'))
    console.log(`Written: ${outputPath.pathname}`)
  }
}

if (import.meta.main) {
  generateTypes()
}
