export const adoptionEventMapping: Record<string, string> = {
  'reason.option': '',
  'reason.other': '',
  'child.brnSearch': '',
  'child.brn': 'adoption.BIRTH_REF',
  'child.name': 'adoption.CHILDS_NAME',
  'child.dob': 'adoption.CHILDS_DOB',
  'child.gender': 'adoption.CHILDS_GENDER',
  'child.birthLocation': 'adoption.CHILDS_BIRTHPLACE',
  'consent.notProvidedOrWaived': '',
  'consent.numberOfParties': '',
  'consenter.cp1.name': '',
  'consenter.cp1.relationship': '',
  'consenter.cp1.relationshipSpecify': '',
  'consenter.cp1.dob': '',
  'consenter.cp1.dobUnknown': '',
  'consenter.cp1.age': '',
  'consenter.cp1.residence': '',
  'consenter.cp1.occupation': '',
  'consenter.cp2.name': '',
  'consenter.cp2.relationship': '',
  'consenter.cp2.relationshipSpecify': '',
  'consenter.cp2.dob': '',
  'consenter.cp2.dobUnknown': '',
  'consenter.cp2.age': '',
  'consenter.cp2.residence': '',
  'consenter.cp2.occupation': '',
  'adoptiveMother.detailsUnavailable': '',
  'adoptiveMother.unavailableReason': '',
  'adoptiveMother.name': 'adoption.MOTHERS_NAME',
  'adoptiveMother.dob': 'adoption.MOTHERS_DOB',
  'adoptiveMother.dobUnknown': '', // Calculate
  'adoptiveMother.age': 'adoption.MOTHERS_AGE',
  'adoptiveMother.maritalStatus': '',
  'adoptiveMother.maidenName': 'adoption.MOTHERS_MAIDEN_NAME',
  'adoptiveMother.placeOfBirth': 'adoption.MOTHERS_BIRTHPLACE',
  'adoptiveMother.nationality': 'adoption.MOTHERS_NATIONALITY',
  'adoptiveMother.idType': '',
  'adoptiveMother.idTypeOther': '',
  'adoptiveMother.idNumber': '',
  'adoptiveMother.residence': 'adoption.MOTHERS_ADDRESS',
  'adoptiveMother.occupation': '',
  'adoptiveFather.detailsUnavailable': '',
  'adoptiveFather.unavailableReason': '',
  'adoptiveFather.name': 'adoption.FATHERS_NAME',
  'adoptiveFather.dob': 'adoption.FATHERS_DOB',
  'adoptiveFather.dobUnknown': '', // Calculate
  'adoptiveFather.age': 'adoption.FATHERS_AGE',
  'adoptiveFather.placeOfBirth': 'adoption.FATHERS_BIRTHPLACE',
  'adoptiveFather.nationality': 'adoption.FATHERS_NATIONALITY',
  'adoptiveFather.idType': '',
  'adoptiveFather.idTypeOther': '',
  'adoptiveFather.idNumber': '',
  'adoptiveFather.residence': 'adoption.FATHERS_ADDRESS',
  'adoptiveFather.occupation': 'adoption.FATHERS_OCCUPATION',
  'adoptionOrder.number': 'adoption.ADOPTION_REF',
  'adoptionOrder.issuingAuthority': 'High Court of the Cook Islands',
  'adoptionOrder.date': 'adoption.DATE_REGISTERED',
  'adoptionOrder.changesChildLegalName': '', // Calculate
  'adoptionOrder.childNewName': 'adoption.CHILDS_NEW_NAME',
}

export const adoptionMetaDataMapping: Record<string, string> = {
  registrationNumber: 'adoption.ADOPTION_REF',
  dateOfRegistration: 'adoption.DATE_REGISTERED',
  registrar: 'adoption.REGISTRAR',
}

export const adoptionNameMapping: Record<string, string> = {
  'adoptiveMother.name.firstname': 'adoption.MOTHERS_NAME',
  'adoptiveMother.name.surname': 'adoption.MOTHERS_SURNAME',
  'adoptiveFather.name.firstname': 'adoption.FATHERS_NAME',
  'adoptiveFather.name.surname': 'adoption.FATHERS_SURNAME',
}

export default {
  ...adoptionEventMapping,
  ...adoptionNameMapping,
  ...adoptionMetaDataMapping,
}
