export const birthEventMapping: Record<string, string> = {
  'informant.contact': '',
  'reason.option': '',
  'reason.other': '',
  'child.name': 'birth.CHILDS_NAME', // or birth.CHILDS_NEW_NAME ??
  'child.dob': 'birth.CHILDS_DOB',
  'child.reason': '',
  'child.gender': 'birth.CHILDS_GENDER',
  'child.placeOfBirth': 'birth.CHILDS_BIRTHPLACE', // Calculate from birth.CHILDS_BIRTHPLACE
  'child.birthLocation': 'birth.CHILDS_BIRTHPLACE',
  'child.birthLocation.privateHome': '',
  'child.birthLocation.other': 'birth.CHILDS_BIRTHPLACE',
  'child.birthType': 'birth.CHILDS_TWIN',
  'child.orderOfBirth.twins': 'birth.CHILDS_TWIN',
  'child.orderOfBirth.triplets': 'birth.CHILDS_TWIN',
  'child.orderOfBirth.higherMultiple': 'birth.CHILDS_TWIN',
  'child.weightAtBirth': '',
  'child.attendantAtBirth': '',
  'child.attendantAtBirth.other': '',
  'child.attendantAtBirth.givenNames': '',
  'child.attendantAtBirth.surname': '',
  'child.isRenamed': 'birth.CHILDS_NEW_NAME', // Calculate !!birth.CHILDS_NEW_NAME
  'nameChange.deedPollNumber1': 'deedpoll.DP_REF',
  'nameChange.newGivenNames1': 'deedpoll.NEW_FIRSTNAMES',
  'nameChange.newSurname1': 'deedpoll.NEW_SURNAME',
  'nameChange.addAnother1': '',
  'nameChange.deedPollNumber2': 'deedpoll.DP_REF',
  'nameChange.newGivenNames2': 'deedpoll.NEW_FIRSTNAMES',
  'nameChange.newSurname2': 'deedpoll.NEW_SURNAME',
  'nameChange.addAnother2': '',
  'nameChange.deedPollNumber3': 'deedpoll.DP_REF',
  'nameChange.newGivenNames3': 'deedpoll.NEW_FIRSTNAMES',
  'nameChange.newSurname3': 'deedpoll.NEW_SURNAME',
  'mother.detailsUnavailable': '',
  'mother.unavailableReason': '',
  'mother.name': 'birth.MOTHERS_NAME',
  'mother.dob': 'birth.MOTHERS_DOB',
  'mother.dobUnknown': '',
  'mother.age': 'birth.MOTHERS_AGE',
  'mother.maritalStatus': '',
  'mother.maidenName': 'birth.MOTHERS_MAIDEN_NAME',
  'mother.placeOfBirth': 'birth.MOTHERS_BIRTHPLACE',
  'mother.nationality': 'birth.MOTHERS_NATIONALITY',
  'mother.idType': '',
  'mother.passport': '',
  'mother.bc': '',
  'mother.other': '',
  'mother.address': 'birth.MOTHERS_ADDRESS',
  'mother.occupation': '',
  'father.detailsUnavailable': '',
  'father.unavailableReason': '',
  'father.name': 'birth.FATHERS_NAME',
  'father.dob': 'birth.FATHERS_DOB',
  'father.dobUnknown': '', // Calculate
  'father.age': 'birth.FATHERS_AGE',
  'father.placeOfBirth': 'birth.FATHERS_BIRTHPLACE',
  'father.nationality': 'birth.FATHERS_NATIONALITY',
  'father.idType': '',
  'father.passport': '',
  'father.bc': '',
  'father.other': '',
  'father.sameAsMotherResidence': '', // Calculate
  'father.address': 'birth.FATHERS_ADDRESS',
  'father.occupation': 'birth.FATHERS_OCCUPATION',
  'informant.relation': 'birth.INFORMANTS_RELATIONSHIP',
  'informant.other.relation': 'birth.INFORMANTS_RELATIONSHIP', // Calculate
  'informant.name': 'birth.INFORMANTS_NAME',
  'informant.dob': '',
  'informant.dobUnknown': '',
  'informant.age': '',
  'informant.nationality': '',
  'informant.idType': '',
  'informant.passport': '',
  'informant.bc': '',
  'informant.other': '',
  'informant.address': 'birth.INFORMANTS_ADDRESS',
  'informant.occupation': 'birth.INFORMANTS_OCCUPATION',
  'informant.phoneNo': '',
  'informant.email': '',
}

export const birthNameMapping: Record<string, string> = {
  'child.name.firstname': 'birth.CHILDS_NAME',
  'child.name.surname': 'birth.FATHERS_SURNAME',
  'mother.name.firstname': 'birth.MOTHERS_NAME',
  'mother.name.surname': 'birth.MOTHERS_SURNAME',
  'father.name.firstname': 'birth.FATHERS_NAME',
  'father.name.surname': 'birth.FATHERS_SURNAME',
}

export const birthMetaDataMapping: Record<string, string> = {
  birthRegistrationNumber: 'birth.BIRTH_REF',
  dateOfRegistration: 'birth.DATE_REGISTERED',
  registrar: 'birth.REGISTRAR',
}

export default {
  ...birthEventMapping,
  ...birthNameMapping,
  ...birthMetaDataMapping,
}
