import { CsvFields } from '../helpers/csvTypes.ts'

export const deathResolver = {
  'informant.contact': '',
  'reason.option': '',
  'reason.other': '',
  'deceased.name': (data: CsvFields) => data.death.NAME_OF_DECEASED,
  'deceased.gender': (data: CsvFields) => data.death.SEX,
  'deceased.dob': '', // Possibly birth.CHILDS_DOB
  'deceased.dobUnknown': '', // Calculate
  'deceased.age': (data: CsvFields) => data.death.AGE,
  'deceased.placeOfBirth': (data: CsvFields) => data.death.WHERE_BORN,
  'deceased.nationality': '',
  'deceased.idType': '',
  'deceased.passport': '',
  'deceased.bc': '',
  'deceased.other': '',
  'deceased.occupation': (data: CsvFields) => data.death.OCCUPATION,
  'deceased.residence': (data: CsvFields) => data.death.USUAL_RESIDENCE,
  'deceased.sincebirth': '',
  'deceased.noOfyearsLivedInCook': (data: CsvFields) =>
    data.death.LENGTH_IN_CIS,
  'deceased.wasMarried': '', // Calculate
  'deceased.dateOfMarriage': (data: CsvFields) => data.death.WHEN_MARRIED,
  'deceased.placeOfMarriage': (data: CsvFields) => data.death.WHERE_MARRIED,
  'deceased.hadLivingChildren': '', // Calculate
  'eventDetails.dateOfDeath': (data: CsvFields) => data.death.WHEN_DIED,
  'eventDetails.mannerOfDeath': '',
  'eventDetails.placeOfDeath': (data: CsvFields) => data.death.WHERE_DIED, // Calculate
  'eventDetails.deathLocation': (data: CsvFields) => data.death.WHERE_DIED,
  'eventDetails.deathLocationOther': (data: CsvFields) => data.death.WHERE_DIED,
  'eventDetails.referredToCoroner': '',
  'eventDetails.fullNameOfCoroner': '',
  'eventDetails.causeOfDeathDeterminedByCoroner': '',
  'eventDetails.causeOfDeathEstablished': '',
  'eventDetails.medicalOfficerName': (data: CsvFields) =>
    data.death.MEDICAL_ATTENDANT,
  'eventDetails.dateLastSeenAlive': (data: CsvFields) =>
    data.death.DATE_LAST_ALIVE,
  'eventDetails.notPersonallyAttended': '',
  'eventDetails.causeOfDeath': (data: CsvFields) => data.death.CAUSE_OF_DEATH,
  'eventDetails.duration': '',
  'eventDetails.ICD10CodeA': '',
  'eventDetails.b.CauseOfDeath': '',
  'eventDetails.b.duration': '',
  'eventDetails.ICD10CodeB': '',
  'eventDetails.c.CauseOfDeath': '',
  'eventDetails.c.duration': '',
  'eventDetails.ICD10CodeC': '',
  'eventDetails.d.CauseOfDeath': '',
  'eventDetails.d.duration': '',
  'eventDetails.ICD10CodeD': '',
  'eventDetails.otherSignificantCondition': '',
  'eventDetails.approximateDuration': '',
  'eventDetails.otherSignificantConditionIfApplicable': '',
  'eventDetails.approximateDuration2': '',
  'burial.burialArrangement': '',
  'burial.dateOfBurial': (data: CsvFields) => data.death.WHEN_BURIED,
  'burial.whereburied': (data: CsvFields) => data.death.WHERE_BURIED,
  'burial.burialPlaceDescription': '',
  'father.detailsNotAvailable': '', //Calculate
  'father.reason': '',
  'father.livingStatus': '',
  'father.name': (data: CsvFields) => data.death.FATHERS_NAME,
  'father.dob': '',
  'father.dobUnknown': '',
  'father.age': '',
  'father.nationality': '',
  'father.idType': '',
  'father.passport': '',
  'father.bc': '',
  'father.other': '',
  'father.occupation': (data: CsvFields) => data.death.FATHERS_OCCUPATION,
  'mother.detailsNotAvailable': '',
  'mother.reason': '',
  'mother.livingStatus': '',
  'mother.name': (data: CsvFields) => data.death.MOTHERS_NAME,
  'mother.maidenName': (data: CsvFields) => data.death.MOTHERS_MAIDEN_NAME,
  'mother.dob': '',
  'mother.dobUnknown': '',
  'mother.age': '',
  'mother.nationality': '',
  'mother.idType': '',
  'mother.passport': '',
  'mother.brn': '',
  'mother.other': '',
  'mother.occupation': '',
  'spouse.detailsNotAvailable': '',
  'spouse.reason': '',
  'spouse.livingStatus': (data: CsvFields) => data.death.AGE_OF_WIDOW,
  'spouse.name': (data: CsvFields) => data.death.WHOM_MARRIED,
  'spouse.dob': '',
  'spouse.dobUnknown': '',
  'spouse.age': (data: CsvFields) => data.death.AGE_OF_WIDOW,
  'spouse.nationality': '',
  'spouse.idType': '',
  'spouse.passport': '',
  'spouse.bc': '',
  'spouse.other': '',
  'spouse.occupation': '',
  'deceased.childrenCount': '', // Can we look these up?
  'deceased.children.1.name': '',
  'deceased.children.1.sex': '',
  'deceased.children.1.age': '',
  'deceased.children.2.name': '',
  'deceased.children.2.sex': '',
  'deceased.children.2.age': '',
  'deceased.children.3.name': '',
  'deceased.children.3.sex': '',
  'deceased.children.3.age': '',
  'deceased.children.4.name': '',
  'deceased.children.4.sex': '',
  'deceased.children.4.age': '',
  'deceased.children.5.name': '',
  'deceased.children.5.sex': '',
  'deceased.children.5.age': '',
  'deceased.children.6.name': '',
  'deceased.children.6.sex': '',
  'deceased.children.6.age': '',
  'deceased.children.7.name': '',
  'deceased.children.7.sex': '',
  'deceased.children.7.age': '',
  'deceased.children.8.name': '',
  'deceased.children.8.sex': '',
  'deceased.children.8.age': '',
  'deceased.children.9.name': '',
  'deceased.children.9.sex': '',
  'deceased.children.9.age': '',
  'deceased.children.10.name': '',
  'deceased.children.10.sex': '',
  'deceased.children.10.age': '',
  'deceased.additionalChildrenSummary': '',
  'informant.relation': (data: CsvFields) => data.death.INFORMANT_DESCRIPTION,
  'informant.other.relation': '',
  'informant.name': '',
  'informant.dob': '',
  'informant.nationality': '',
  'informant.idType': '',
  'informant.passport': '',
  'informant.bc': '',
  'informant.other': '',
  'informant.occupation': '',
  'informant.addressSameAs': '',
  'informant.address': (data: CsvFields) => data.death.INFORMANT_RESIDENCE,
  'informant.phoneNo': '',
  'informant.email': '',
}

export const deathMetaDataMapping: Record<string, string> = {
  registrationNumber: 'death.DEATH_NUMBER',
  dateOfRegistration: 'death.DATE_REGISTERED',
  placeOfRegistration: 'death.PLACE_OF_REGISTRATION',
  registrar: 'death.REGISTRAR',
}
