// Note: Divorce mappings use the same legacy field names as marriage registration
export const divorceEventMapping: Record<string, string> = {
  'informant.contact': '',
  'reason.option': '',
  'reason.other': '',
  'applicationDetails.typeOfApplication': '',
  'applicationDetails.applicantParty': '',
  'marriageDetails.marriageRegistrationNumber': 'marriage.NOTICE_NUMBER',
  'marriageDetails.dateOfMarriage': 'marriage.MARRIAGE_DATE',
  'marriageDetails.placeOfMarriage': 'marriage.MARRIAGE_PLACE',
  'marriageDetails.bridegroomGivenNames': 'marriage.GROOM_FIRSTNAME',
  'marriageDetails.bridegroomDob': 'marriage.GROOM_DOB',
  'marriageDetails.bridegroompob': 'marriage.GROOM_BIRTHPLACE',
  'marriageDetails.bridegroomOccupation': 'marriage.GROOM_OCCUPATION',
  'marriageDetails.bridegroomConjugalStatus': 'marriage.GROOM_STATUS',
  'marriageDetails.bridegroomDecreeAbsoluteDate': '',
  'marriageDetails.bridegroomFormerWifeDeathDate': 'marriage.GROOM_DOD_WIDOW',
  'marriageDetails.residence': 'marriage.GROOM_RESIDENCE',
  'marriageDetails.brideName': 'marriage.BRIDE_FIRSTNAME',
  'marriageDetails.brideDob': 'marriage.BRIDE_DOB',
  'marriageDetails.bridePlaceOfBirth': 'marriage.BRIDE_BIRTHPLACE',
  'marriageDetails.brideOccupation': 'marriage.BRIDE_OCCUPATION',
  'marriageDetails.brideConjugalStatus': 'marriage.BRIDE_STATUS',
  'marriageDetails.brideDecreeAbsoluteDate': '',
  'marriageDetails.brideFormerHusbandDeathDate': 'marriage.BRIDE_DOD_WIDOWER',
  'marriageDetails.brideResidence': 'marriage.BRIDE_RESIDENCE',
  'divorceOrderDetails.orderNumber': '',
  'divorceOrderDetails.issuingAuthority': '',
  'divorceOrderDetails.orderDate': '',
}
