export const DEFAULT_FIELD_MAPPINGS = {
  // birth

  'birth.child.gender': 'child.gender',
  'birth.child.childBirthDate': 'child.dob',
  'birth.child.placeOfBirth': 'child.placeOfBirth',
  'birth.child.birthLocation': 'child.birthLocation',
  'birth.child.attendantAtBirth': 'child.attendantAtBirth',
  'birth.child.birthType': 'child.birthType',
  'birth.child.weightAtBirth': 'child.weightAtBirth',

  'birth.informant.informantNationalId': 'informant.nid',
  'birth.informant.informantPassport': 'informant.passport',
  'birth.informant.informantBirthRegistrationNumber': 'informant.brn',
  'birth.informant.informantBirthDate': 'informant.dob',
  'birth.informant.registrationPhone': 'informant.phoneNo',
  'birth.informant.registrationEmail': 'informant.email',
  'birth.informant.informantType': 'informant.relation',
  'birth.informant.otherInformantType': 'informant.other.relation',
  'birth.informant.exactDateOfBirthUnknown': 'informant.dobUnknown',
  'birth.informant.ageOfIndividualInYears': 'informant.age',
  'birth.informant.nationality': 'informant.nationality',

  'birth.mother.motherNationalId': 'mother.nid',
  'birth.mother.motherPassport': 'mother.passport',
  'birth.mother.motherBirthRegistrationNumber': 'mother.brn',
  'birth.mother.detailsExist': 'mother.detailsNotAvailable',
  'birth.mother.reasonNotApplying': 'mother.reason',
  'birth.mother.motherBirthDate': 'mother.dob',
  'birth.mother.exactDateOfBirthUnknown': 'mother.dobUnknown',
  'birth.mother.ageOfIndividualInYears': 'mother.age',
  'birth.mother.nationality': 'mother.nationality',
  'birth.mother.maritalStatus': 'mother.maritalStatus',
  'birth.mother.educationalAttainment': 'mother.educationalAttainment',
  'birth.mother.occupation': 'mother.occupation',
  'birth.mother.multipleBirth': 'mother.previousBirths',

  'birth.father.fatherNationalId': 'father.nid',
  'birth.father.fatherPassport': 'father.passport',
  'birth.father.fatherBirthRegistrationNumber': 'father.brn',
  'birth.father.detailsExist': 'father.detailsNotAvailable',
  'birth.father.reasonNotApplying': 'father.reason',
  'birth.father.fatherBirthDate': 'father.dob',
  'birth.father.exactDateOfBirthUnknown': 'father.dobUnknown',
  'birth.father.ageOfIndividualInYears': 'father.age',
  'birth.father.nationality': 'father.nationality',
  'birth.father.maritalStatus': 'father.maritalStatus',
  'birth.father.educationalAttainment': 'father.educationalAttainment',
  'birth.father.occupation': 'father.occupation',

  'birth.documents.uploadDocForChildDOB': 'documents.proofOfBirth',
  'birth.documents.uploadDocForMother': 'documents.proofOfMother',
  'birth.documents.uploadDocForFather': 'documents.proofOfFather',
  'birth.documents.uploadDocForInformant': 'documents.proofOfInformant',
  'birth.documents.uploadDocForProofOfLegalGuardian': 'documents.proofOther',

  // death

  'death.deceased.gender': 'deceased.gender',
  'death.deceased.deceasedBirthDate': 'deceased.dob',
  'death.deceased.exactDateOfBirthUnknown': 'deceased.dobUnknown',
  'death.deceased.ageOfIndividualInYears': 'deceased.age',
  'death.deceased.nationality': 'deceased.nationality',
  'death.deceased.deceasedNationalId': 'deceased.nid',
  'death.deceased.deceasedPassport': 'deceased.passport',
  'death.deceased.deceasedBirthRegistrationNumber': 'deceased.brn',
  'death.deceased.maritalStatus': 'deceased.maritalStatus',

  'death.deathEvent.deathDate': 'eventDetails.date',
  'death.deathEvent.mannerOfDeath': 'eventDetails.mannerOfDeath',
  'death.deathEvent.causeOfDeathEstablished':
    'eventDetails.causeOfDeathEstablished',
  'death.deathEvent.causeOfDeathMethod': 'eventDetails.sourceCauseDeath',
  'death.deathEvent.deathDescription': 'eventDetails.description',
  'death.deathEvent.placeOfDeath': 'eventDetails.placeOfDeath',
  'death.deathEvent.deathLocation': 'eventDetails.deathLocation',

  'death.informant.informantType': 'informant.relation',
  'death.informant.otherInformantType': 'informant.other.relation',
  'death.informant.informantBirthDate': 'informant.dob',
  'death.informant.exactDateOfBirthUnknown': 'informant.dobUnknown',
  'death.informant.ageOfIndividualInYears': 'informant.age',
  'death.informant.nationality': 'informant.nationality',
  'death.informant.informantNationalId': 'informant.nid',
  'death.informant.informantPassport': 'informant.passport',
  'death.informant.informantBirthRegistrationNumber': 'informant.brn',
  'death.informant.primaryAddressSameAsOtherPrimary': 'informant.addressSameAs',
  'death.informant.registrationPhone': 'informant.phoneNo',
  'death.informant.registrationEmail': 'informant.email',

  'death.spouse.detailsExist': 'spouse.detailsNotAvailable',
  'death.spouse.reasonNotApplying': 'spouse.reason',
  'death.spouse.spouseBirthDate': 'spouse.dob',
  'death.spouse.exactDateOfBirthUnknown': 'spouse.dobUnknown',
  'death.spouse.ageOfIndividualInYears': 'spouse.age',
  'death.spouse.nationality': 'spouse.nationality',
  'death.spouse.spouseNationalId': 'spouse.nid',
  'death.spouse.spousePassport': 'spouse.passport',
  'death.spouse.spouseBirthRegistrationNumber': 'spouse.brn',

  'death.documents.uploadDocForDeceased': 'documents.proofOfDeceased',
  'death.documents.uploadDocForInformant': 'documents.proofOfInformant',
  'death.documents.uploadDocForDeceasedDeath': 'documents.proofOfDeath',
  'death.documents.uploadDocForCauseOfDeath': 'documents.proofOfCauseOfDeath',
}

export const CUSTOM_FIELD_MAPPINGS = {
  'birth.child.child-view-group.reasonForLateRegistration': 'child.reason',
  'birth.informant.informant-view-group.informantIdType': 'informant.idType',
  'birth.mother.mother-view-group.motherIdType': 'mother.idType',
  'birth.father.father-view-group.fatherIdType': 'father.idType',
  'death.deceased.deceased-view-group.deceasedIdType': 'deceased.idType',
  'death.deceased.deceased-view-group.numberOfDependants':
    'deceased.numberOfDependants',
  'death.deathEvent.death-event-details.reasonForLateRegistration':
    'eventDetails.reasonForLateRegistration',
  'death.informant.informant-view-group.informantIdType': 'informant.idType',
  'death.spouse.spouse-view-group.spouseIdType': 'spouse.idType',
}
