export const v1IgnoreList = [
  // I think this is all MOSIP stuff
  "birth.informant.informant-view-group.idReader",
  "birth.informant.esignetCallback",
  "birth.informant.esignetLoader",
  "birth.informant.informant-view-group.verified",
  "birth.informant.idVerified.",
  "birth.informant.idFailed.",
  "birth.informant.idAuthenticated.",
  "birth.informant.idFailedFetchIdDetails.",
  "birth.mother.mother-view-group.idReader",
  "birth.mother.esignetCallback",
  "birth.mother.esignetLoader",
  "birth.mother.mother-view-group.verified",
  "birth.mother.idVerified.",
  "birth.mother.idFailed.",
  "birth.mother.idAuthenticated.",
  "birth.mother.idFailedFetchIdDetails.",
  "birth.father.father-view-group.idReader",
  "birth.father.esignetCallback",
  "birth.father.esignetLoader",
  "birth.father.father-view-group.verified",
  "birth.father.idVerified.",
  "birth.father.idFailed.",
  "birth.father.idAuthenticated.",
  "birth.father.idFailedFetchIdDetails.",

  "death.deceased.deceased-view-group.idReader",
  "death.deceased.esignetCallback",
  "death.deceased.esignetLoader",
  "death.deceased.deceased-view-group.verified",
  "death.deceased.idVerified.",
  "death.deceased.idFailed.",
  "death.deceased.idAuthenticated.",
  "death.deceased.idFailedFetchIdDetails.",

  "death.informant.informant-view-group.idReader",
  "death.informant.esignetCallback",
  "death.informant.esignetLoader",
  "death.informant.informant-view-group.verified",
  "death.informant.idVerified.",
  "death.informant.idFailed.",
  "death.informant.idAuthenticated.",
  "death.informant.idFailedFetchIdDetails.",

  "death.spouse.spouse-view-group.idReader",
  "death.spouse.esignetCallback",
  "death.spouse.esignetLoader",
  "death.spouse.spouse-view-group.verified",
  "death.spouse.idVerified.",
  "death.spouse.idFailed.",
  "death.spouse.idAuthenticated.",
  "death.spouse.idFailedFetchIdDetails.",
  // not supporting rural/urban
  "birth.child.ruralOrUrbanPlaceofbirth",
  "birth.informant.ruralOrUrbanPrimaryInformant",
  "birth.mother.ruralOrUrbanPrimaryMother",
  "birth.father.ruralOrUrbanPrimaryFather",

  "death.deceased.ruralOrUrbanPrimaryDeceased",
  "death.deathEvent.ruralOrUrbanPlaceofdeath",
  "death.spouse.ruralOrUrbanPrimarySpouse",
  "death.informant.ruralOrUrbanPrimaryInformant",
];

// Mention fields
const base = "birth.mention.mention-view-group";
const fields = [
  "detailsMentionExist",
  "typeOfMention",
  "recognitionActNumber",
  "recognitionDate",
  "recognitionPlace",
  "childFamilyName",
  "childFirstName",
  "mentionChildNID",
  "simpleAdoptionActNumber",
  "simpleAdoptionDate",
  "simpleAdoptionParent1FamilyName",
  "simpleAdoptionParent1FirstName",
  "simpleAdoptionParent1NID",
  "simpleAdoptionParent2FamilyName",
  "simpleAdoptionParent2FirstName",
  "simpleAdoptionParent2NID",
  "judicialAdoptionActNumber",
  "judicialAdoptionDate",
  "judicialAdoptionJudgementDecisionNumber",
  "judicialAdoptionJudgementDecisionDate",
  "judicialAdoptionTribunalOfFirstInstanceAct",
  "judicialAdoptionParent1FamilyName",
  "judicialAdoptionParent1FirstName",
  "judicialAdoptionParent1NID",
  "judicialAdoptionParent2FamilyName",
  "judicialAdoptionParent2FirstName",
  "judicialAdoptionParent2NID",
  "nameChangeActNumber",
  "nameChangeDate",
  "nameChangeJudgementDecisionNumber",
  "nameChangeJudgementDecisionDate",
  "nameChangeTribunalOfFirstInstanceAct",
  "modification",
  "marriageActNumber",
  "marriageDate",
  "marriageJudgementDecisionNumber",
  "marriageJudgementDecisionDate",
  "marriageTribunalOfFirstInstanceAct",
  "brideOrGroomFamilyName",
  "brideOrGroomFirstName",
  "brideOrGroomNID",
  "divorceActNumber",
  "divorceDate",
  "divorcePlace",
  "wifeOrHusbandFamilyName",
  "wifeOrHusbandFirstName",
  "wifeOrHusbandNID",
  "deathActNumber",
  "deathDate",
  "deathPlace",
  "deathdateOfDeath",
  "deathDeathPlace",
  "notes",
];

const mentionFields = Array.from({ length: 10 }, (_, i) =>
  fields.map((field) => `${base}.${field}__${i}`)
).flat();

// Add all the mention fields to the existing ignore list
v1IgnoreList.push(...mentionFields);
