// This file is auto-generated by typeGenerator.ts. Do not edit manually.
import type { Address, Name } from './sharedTypes_generated.ts'
import type { Country, CrvsDate, Facility } from './staticTypes.ts'

export type ChildGender = 'male' | 'female' | 'unknown'
export type ChildPlaceOfBirth = 'HEALTH_FACILITY' | 'PRIVATE_HOME' | 'OTHER'
export type ChildAttendantAtBirth = 'PHYSICIAN' | 'NURSE' | 'MIDWIFE' | 'OTHER_PARAMEDICAL_PERSONNEL' | 'LAYPERSON' | 'TRADITIONAL_BIRTH_ATTENDANT' | 'NONE'
export type ChildBirthType = 'SINGLE' | 'TWIN' | 'TRIPLET' | 'QUADRUPLET' | 'HIGHER_MULTIPLE_DELIVERY'
export type InformantRelation = 'MOTHER' | 'FATHER' | 'OTHER' | 'GRANDFATHER' | 'GRANDMOTHER' | 'BROTHER' | 'SISTER' | 'LEGAL_GUARDIAN'
export type InformantIdType = 'NATIONAL_ID' | 'PASSPORT' | 'BIRTH_REGISTRATION_NUMBER' | 'NONE'
export type MotherIdType = 'NATIONAL_ID' | 'PASSPORT' | 'BIRTH_REGISTRATION_NUMBER' | 'NONE'
export type MotherMaritalStatus = 'SINGLE' | 'MARRIED' | 'WIDOWED' | 'DIVORCED' | 'SEPARATED' | 'NOT_STATED'
export type MotherEducationalAttainment = 'NO_SCHOOLING' | 'PRIMARY_ISCED_1' | 'POST_SECONDARY_ISCED_4' | 'FIRST_STAGE_TERTIARY_ISCED_5'
export type FatherIdType = 'NATIONAL_ID' | 'PASSPORT' | 'BIRTH_REGISTRATION_NUMBER' | 'NONE'
export type FatherAddressSameAs = 'YES' | 'NO'
export type FatherMaritalStatus = 'SINGLE' | 'MARRIED' | 'WIDOWED' | 'DIVORCED' | 'SEPARATED' | 'NOT_STATED'
export type FatherEducationalAttainment = 'NO_SCHOOLING' | 'PRIMARY_ISCED_1' | 'POST_SECONDARY_ISCED_4' | 'FIRST_STAGE_TERTIARY_ISCED_5'

export interface BirthFields {
  'child.nid'?: string
  'child.name'?: Name
  'child.gender'?: ChildGender
  'child.dob'?: CrvsDate
  'child.reason'?: string
  'child.placeOfBirth'?: ChildPlaceOfBirth
  'child.birthLocation'?: Facility
  'child.birthLocation.privateHome'?: Address
  'child.birthLocation.other'?: Address
  'child.attendantAtBirth'?: ChildAttendantAtBirth
  'child.birthType'?: ChildBirthType
  'child.weightAtBirth'?: number
  'informant.relation'?: InformantRelation
  'informant.other.relation'?: string
  'informant.name'?: Name
  'informant.dob'?: CrvsDate
  'informant.dobUnknown'?: boolean
  'informant.age'?: number
  'informant.nationality'?: Country
  'informant.idType'?: InformantIdType
  'informant.nid'?: string
  'informant.passport'?: string
  'informant.brn'?: string
  'informant.address'?: Address
  'informant.phoneNo'?: string
  'informant.email'?: string
  'mother.detailsNotAvailable'?: boolean
  'mother.reason'?: string
  'mother.name'?: Name
  'mother.dob'?: CrvsDate
  'mother.dobUnknown'?: boolean
  'mother.age'?: number
  'mother.nationality'?: Country
  'mother.idType'?: MotherIdType
  'mother.nid'?: string
  'mother.passport'?: string
  'mother.brn'?: string
  'mother.address'?: Address
  'mother.maritalStatus'?: MotherMaritalStatus
  'mother.educationalAttainment'?: MotherEducationalAttainment
  'mother.occupation'?: string
  'mother.previousBirths'?: number
  'father.detailsNotAvailable'?: boolean
  'father.reason'?: string
  'father.name'?: Name
  'father.dob'?: CrvsDate
  'father.dobUnknown'?: boolean
  'father.age'?: number
  'father.nationality'?: Country
  'father.idType'?: FatherIdType
  'father.nid'?: string
  'father.passport'?: string
  'father.brn'?: string
  'father.addressSameAs'?: FatherAddressSameAs
  'father.address'?: Address
  'father.maritalStatus'?: FatherMaritalStatus
  'father.educationalAttainment'?: FatherEducationalAttainment
  'father.occupation'?: string
}
