// This file is auto-generated by typeGenerator.ts. Do not edit manually.
import type { Address, Name } from './sharedTypes_generated.ts'
import type { Country, CrvsDate, Facility } from './staticTypes.ts'

export type DeceasedGender = 'male' | 'female' | 'unknown'
export type DeceasedIdType = 'NATIONAL_ID' | 'PASSPORT' | 'BIRTH_REGISTRATION_NUMBER' | 'NONE'
export type DeceasedMaritalStatus = 'SINGLE' | 'MARRIED' | 'WIDOWED' | 'DIVORCED' | 'SEPARATED' | 'NOT_STATED'
export type EventDetailsMannerOfDeath = 'MANNER_NATURAL' | 'MANNER_ACCIDENT' | 'MANNER_SUICIDE' | 'MANNER_HOMICIDE' | 'MANNER_UNDETERMINED'
export type EventDetailsSourceCauseDeath = 'PHYSICIAN' | 'LAY_REPORTED' | 'VERBAL_AUTOPSY' | 'MEDICALLY_CERTIFIED'
export type EventDetailsPlaceOfDeath = 'HEALTH_FACILITY' | 'DECEASED_USUAL_RESIDENCE' | 'OTHER'
export type InformantRelation = 'SPOUSE' | 'SON' | 'DAUGHTER' | 'SON_IN_LAW' | 'DAUGHTER_IN_LAW' | 'MOTHER' | 'FATHER' | 'GRANDSON' | 'GRANDDAUGHTER' | 'OTHER'
export type InformantIdType = 'NATIONAL_ID' | 'PASSPORT' | 'BIRTH_REGISTRATION_NUMBER' | 'NONE'
export type InformantAddressSameAs = 'YES' | 'NO'
export type SpouseIdType = 'NATIONAL_ID' | 'PASSPORT' | 'BIRTH_REGISTRATION_NUMBER' | 'NONE'
export type SpouseAddressSameAs = 'YES' | 'NO'

export interface DeathFields {
  'deceased.name'?: Name
  'deceased.gender'?: DeceasedGender
  'deceased.dob'?: CrvsDate
  'deceased.dobUnknown'?: boolean
  'deceased.age'?: number
  'deceased.nationality'?: Country
  'deceased.idType'?: DeceasedIdType
  'deceased.nid'?: string
  'deceased.passport'?: string
  'deceased.brn'?: string
  'deceased.maritalStatus'?: DeceasedMaritalStatus
  'deceased.numberOfDependants'?: number
  'deceased.address'?: Address
  'eventDetails.date'?: CrvsDate
  'eventDetails.reasonForLateRegistration'?: string
  'eventDetails.mannerOfDeath'?: EventDetailsMannerOfDeath
  'eventDetails.causeOfDeathEstablished'?: boolean
  'eventDetails.sourceCauseDeath'?: EventDetailsSourceCauseDeath
  'eventDetails.description'?: string
  'eventDetails.placeOfDeath'?: EventDetailsPlaceOfDeath
  'eventDetails.deathLocation'?: Facility
  'eventDetails.deathLocationOther'?: Address
  'informant.relation'?: InformantRelation
  'informant.other.relation'?: string
  'informant.name'?: Name
  'informant.dob'?: CrvsDate
  'informant.dobUnknown'?: boolean
  'informant.age'?: number
  'informant.nationality'?: Country
  'informant.idType'?: InformantIdType
  'informant.nid'?: string
  'informant.passport'?: string
  'informant.brn'?: string
  'informant.addressSameAs'?: InformantAddressSameAs
  'informant.address'?: Address
  'informant.phoneNo'?: string
  'informant.email'?: string
  'spouse.detailsNotAvailable'?: boolean
  'spouse.reason'?: string
  'spouse.name'?: Name
  'spouse.dob'?: CrvsDate
  'spouse.dobUnknown'?: boolean
  'spouse.age'?: number
  'spouse.nationality'?: Country
  'spouse.idType'?: SpouseIdType
  'spouse.nid'?: string
  'spouse.passport'?: string
  'spouse.brn'?: string
  'spouse.addressSameAs'?: SpouseAddressSameAs
  'spouse.address'?: Address
}
