// This file is auto-generated by typeGenerator.ts. Do not edit manually.
import type { AdminStructure, Country } from './staticTypes.ts'

export type Name = {
  firstname?: string
  middlename?: string
  surname?: string
}

export type DomesticAddress = {
  addressType: 'DOMESTIC'
  country: Country
  administrativeArea?: AdminStructure
  streetLevelDetails: {
    town?: string
    residentialArea?: string
    street?: string
    number?: string
    zipCode?: string
  }
}

export type InternationalAddress = {
  addressType: 'INTERNATIONAL'
  country: Country
  administrativeArea?: AdminStructure
  streetLevelDetails: {
    state?: string
    district2?: string
    cityOrTown?: string
    addressLine1?: string
    addressLine2?: string
    addressLine3?: string
    postcodeOrZip?: string
  }
}

export type Address = DomesticAddress | InternationalAddress
