// This file is auto-generated by typeGenerator.ts. Do not edit manually.
import type { Name } from './sharedTypes_generated.ts'
import type { CrvsDate } from './staticTypes.ts'

export type CorrectionIdentityCheckVerified = 'VERIFIED'
export type CorrectionRequestSupportingDocuments = 'ATTEST' | 'NOT_NEEDED'

export interface TennisClubMembershipFields {
  'correction.identity-check.verified'?: CorrectionIdentityCheckVerified
  'correction.request.supportingDocuments'?: CorrectionRequestSupportingDocuments
  'correction.request.reason'?: string
  'applicant.name'?: Name
  'applicant.dob'?: CrvsDate
  'applicant.tob'?: string
  'applicant.image.label'?: string
  'applicant.isRecommendedByFieldAgent'?: boolean
  'senior-pass.id'?: string
  'recommender.none'?: boolean
  'recommender.name'?: Name
  'recommender.device'?: string
  'recommender.fullHonorificName'?: string
  'recommender.role'?: string
  'recommender.id'?: string
  'recommender2.id'?: string
  'recommender3.id'?: string
  'recommender4.id'?: string
  'recommender5.id'?: string
}
