export type LengthInCisValue =
  | { years: number }
  | { sinceBirth: true }
  | ((age: number | null, date: string) => { years: number })

export const lengthInCis: Record<string, LengthInCisValue> = {
  // Unknown/Invalid entries
  '-': { years: 0 },
  UNKNOWN: { years: 0 },

  // Minutes
  '1 MINS': { years: 0 },
  '5 MINS': { years: 0 },
  '30 MIN': { years: 0 },
  '30 MINUTES': { years: 0 },
  '52 MINUTES': { years: 0 },
  'FEW MINUTES': { years: 0 },

  // Hours
  '1 HOUR': { years: 0 },
  '1 HR': { years: 0 },
  '1HR': { years: 0 },
  '1/2 HR': { years: 0 },
  '2 1/2 HOURS': { years: 0 },
  '2 1/2 HRS': { years: 0 },
  '2 HOURS': { years: 0 },
  '2 HRS': { years: 0 },
  '3 HRS': { years: 0 },
  '4 HOURS': { years: 0 },
  '4 HRS': { years: 0 },
  '5 HRS': { years: 0 },
  '6 HOURS': { years: 0 },
  '6 HRS': { years: 0 },
  '7 HOURS': { years: 0 },
  '7 HRS': { years: 0 },
  '8 HRS': { years: 0 },
  '9 HRS': { years: 0 },
  '10 HOURS': { years: 0 },
  '10 HRS': { years: 0 },
  '11 HOURS': { years: 0 },
  '12 HOURS': { years: 0 },
  '12 HRS': { years: 0 },
  '12/24 HRS': { years: 0 },
  '13 HRS': { years: 0 },
  '14 HRS': { years: 0 },
  '15 HRS': { years: 0 },
  '16 HOURS': { years: 0 },
  '16 HRS': { years: 0 },
  '18 HRS': { years: 0 },
  '20 HOURS': { years: 0 },
  '24 HOURS': { years: 0 },
  '24 HRS': { years: 0 },
  '26 HRS': { years: 0 },
  '27 HRS': { years: 0 },
  '31 HRS': { years: 0 },
  '43 HOURS': { years: 0 },
  '48 HRS': { years: 0 },
  HOURS: { years: 0 },
  'FEW HRS': { years: 0 },
  'ONE HOUR': { years: 0 },
  'SEVERAL HR': { years: 0 },

  // Days
  '1 DAY': { years: 0 },
  '1 DAY 22YRS': { years: 22 }, // Appears to be data entry error, using the years part
  '1/2 DAY': { years: 0 },
  '1/4 DAY': { years: 0 },
  '2  DAYS': { years: 0 },
  '2 DAYS': { years: 0 },
  '3 1/2 DAYS': { years: 0 },
  '3 DAYS': { years: 0 },
  '4 DAYS': { years: 0 },
  '5 DAYS': { years: 0 },
  '6 DAYS': { years: 0 },
  '6DAYS': { years: 0 },
  '7 DAYS': { years: 0 },
  '8 DAY': { years: 0 },
  '8 DAYS': { years: 0 },
  '9 DAYS': { years: 0 },
  '10 DAYS': { years: 0 },
  '11 DAYS': { years: 0 },
  '12 DAYS': { years: 0 },
  '13 DAYS': { years: 0 },
  '14 DAYS': { years: 0 },
  '16 DAYS': { years: 0 },
  '17 DAYS': { years: 0 },
  '18 DAYS': { years: 0 },
  '19 DAYS': { years: 0 },
  '20 DAYS': { years: 0 },
  '21 DAYS': { years: 0 },
  '23 DAYS': { years: 0 },
  '25 DAYS': { years: 0 },
  '26 DAYS': { years: 0 },
  '27 DAYS': { years: 0 },
  '28 DAYS': { years: 0 },
  '30 DAYS': { years: 0 },
  '34 DAYS': { years: 0 },
  '35DAYS': { years: 0 },
  '37 DAYS': { years: 0 },
  '39 DAYS': { years: 0 },
  '44 DAYS': { years: 0 },
  '48 DAYS': { years: 0 },
  '51 DAYS': { years: 0 },
  'FEW DAYS': { years: 0 },

  // Weeks
  '1 WEEK': { years: 0 },
  '1 WK': { years: 0 },
  '2 1/2 WEEKS': { years: 0 },
  '2 WEEKS': { years: 0 },
  '2 WKS': { years: 0 },
  '3 WEEKS': { years: 0 },
  '3 WKS': { years: 0 },
  '4 WEEKS': { years: 0 },
  '4 WKS': { years: 0 },
  '5 WEEKS': { years: 0 },
  '5 WKS': { years: 0 },
  '6 WEEKS': { years: 0 },
  '6 WKS': { years: 0 },
  '7 WKS': { years: 0 },
  '8 WEEKS': { years: 0 },
  '10 WEEKS': { years: 0 },
  '10 WKS': { years: 0 },
  '20 WKS': { years: 0 },
  '35 WKS': { years: 0 },
  '36 WKS': { years: 0 },
  'ONE WEEK': { years: 0 },
  'THREE WEEKS': { years: 0 },
  'APPROXIMATELY 2 WKS': { years: 0 },

  // Months
  '1 MONTH': { years: 0 },
  '1 MONTH 1 WK': { years: 0 },
  '1 MONTH 2 WKS': { years: 0 },
  '1 MONTH 4 DAYS': { years: 0 },
  '1 MONTH 8 DAYS': { years: 0 },
  '1 MONTH, 5 DAYS': { years: 0 },
  '1 MONTH/4 DAYS': { years: 0 },
  '1 MONTH/5 DAYS': { years: 0 },
  '1 MONTHS': { years: 0 },
  '2 1/2 MONTHS': { years: 0 },
  '2 AND 1/2 MONTHS': { years: 0 },
  '2 MONTHS': { years: 0 },
  '2 MONTHS OLD': { years: 0 },
  '2 MONTHS/1 WEEK': { years: 0 },
  '3  MONTHS': { years: 0 },
  '3 1/2 MONTHS': { years: 0 },
  '3 MONTHS': { years: 0 },
  '3 MONTHS 1 DAY': { years: 0 },
  '3 MONTHS 8 DAYS': { years: 0 },
  '4 1/2 MONTHS': { years: 0 },
  '4 MONTH': { years: 0 },
  '4 MONTHS': { years: 0 },
  '4 MONTHS 4 DAYS': { years: 0 },
  '4 MONTHS/1 WEEK': { years: 0 },
  '4MTHS': { years: 0 },
  '5 AND 1/2 MONTHS': { years: 0 },
  '5 MONTHS': { years: 0 },
  '5 MONTHS 10 DAYS': { years: 0 },
  '5 MONTHS 5 DAYS': { years: 0 },
  '5 MONTHS 6 DAYS': { years: 0 },
  '6 MONTHS': { years: 0 },
  '7 1/2 MONTHS': { years: 0 },
  '7 MONTHS': { years: 0 },
  '7 MONTHS & 2 WEEKS': { years: 0 },
  '8 MONTHS': { years: 0 },
  '9 MONTHS': { years: 0 },
  '10 MONTHS': { years: 0 },
  '11 MONTHS': { years: 0 },
  '13 MONTHS': { years: 1 }, // Over a year
  '15 MONTHS': { years: 1 },
  '16 MONTHS': { years: 1 },
  '18 MONTHS': { years: 1 },
  '19 MONTHS': { years: 1 },
  '20 MONTHS': { years: 1 },
  '28 MONTHS': { years: 2 },
  MONTHS: { years: 0 },
  'MONTHS AND HALF': { years: 0 },
  'COUPLE OF MONTHS': { years: 0 },
  'FEW MONTHS': { years: 0 },
  'JUST OVER 1 MONTH': { years: 0 },
  'SOME MONTHS': { years: 0 },
  'FIFTEEN MONTHS, 26 D': { years: 1 },

  // Years - 1
  '1': { years: 1 }, // Ambiguous, assuming less than a year
  '1 1/2 YR': { years: 1.5 },
  '1 1/2 YRS': { years: 1.5 },
  '1 1/2YRS': { years: 1.5 },
  '1 YEAR': { years: 1 },
  '1 YEAR & 2 MONTHS': { years: 1 },
  '1 YEAR 2 MONTHS': { years: 1 },
  '1 YEAR, 10 MONTHS': { years: 1 },
  '1 YEAR, 2 MONTHS': { years: 1 },
  '1 YEAR, 5 MONTHS': { years: 1 },
  '1 YR': { years: 1 },
  '1 YR & 6 MONTHS': { years: 1 },
  '1 YR - MONTH': { years: 1 },
  '1 YR 1 MTH': { years: 1 },
  '1 YR 10 MNTHS': { years: 1 },
  '1 YR 3 MNTHS': { years: 1 },
  '1 YR 9 MONTHS': { years: 1 },
  '1 YRS': { years: 1 },
  '1YR 3 MNTHS': { years: 1 },
  'ABOUT 1 YR': { years: 1 },
  'ONE YEAR': { years: 1 },
  'ONE YR': { years: 1 },
  'I YRS': { years: 1 },

  // Years - 2
  '2  1/2 YEARS': { years: 2.5 },
  '2 1/2 YRS': { years: 2.5 },
  '2 AND 1/2': { years: 2.5 },
  '2 YEARS': { years: 2 },
  '2 YEARS AND OVER': { years: 2 },
  '2 YRS': { years: 2 },
  '2YRS': { years: 2 },

  // Years - 3
  '3 1/2 YRS': { years: 3.5 },
  '3 YEARS': { years: 3 },
  '3 YRS': { years: 3 },
  'ABOUT 3 YRS': { years: 3 },

  // Years - 4
  '4 AND 1/2 YEARS': { years: 4.5 },
  '4 YEARS': { years: 4 },
  '4 YRS': { years: 4 },
  '4YRS': { years: 4 },
  'OVER 4 YRS': { years: 4 },

  // Years - 5
  '5 YEARS': { years: 5 },
  '5 YEARS & 2 MONTHS': { years: 5 },
  '5 YRS': { years: 5 },
  '5YRS': { years: 5 },

  // Years - 6
  '6 YEARS': { years: 6 },
  '6 YRS': { years: 6 },
  '6YRS': { years: 6 },

  // Years - 7
  '7 YEARS': { years: 7 },
  '7 YEARS & 10 MONTHS': { years: 7 },
  '7 YRS': { years: 7 },
  '7YRS': { years: 7 },

  // Years - 8
  '8 YEARS': { years: 8 },
  '8 YRS': { years: 8 },
  '8YRS': { years: 8 },

  // Years - 9
  '9 YEARS': { years: 9 },
  '9 YRS': { years: 9 },

  // Years - 10
  '10 YEARS': { years: 10 },
  '10 YRS': { years: 10 },
  '10YRS': { years: 10 },
  'ABOUT 10 YRS': { years: 10 },
  'OVER 10 YRS': { years: 10 },
  'TEN YRS': { years: 10 },

  // Years - 11-19
  '11 YEARS': { years: 11 },
  '11 YRS': { years: 11 },
  '12 YEARS': { years: 12 },
  '12 YRS': { years: 12 },
  '13 YRS': { years: 13 },
  '14 YEARS': { years: 14 },
  '14 YRS': { years: 14 },
  '14YRS': { years: 14 },
  '15 YEARS': { years: 15 },
  '15 YRS': { years: 15 },
  '16 YEARS': { years: 16 },
  '16 YRS': { years: 16 },
  '16YRS': { years: 16 },
  'ABOUT 16 YRS': { years: 16 },
  '17 YEARS': { years: 17 },
  '17 YRS': { years: 17 },
  '17YRS': { years: 17 },
  '18 YEARS': { years: 18 },
  '18 YRS': { years: 18 },
  '18YRS': { years: 18 },
  '19 YRS': { years: 19 },

  // Years - 20-29
  '20': { years: 20 },
  '20 + YRS': { years: 20 },
  '20 YEARS': { years: 20 },
  '20 YRS': { years: 20 },
  '20+ YRS': { years: 20 },
  '20YRS': { years: 20 },
  'OVER 20 YRS': { years: 20 },
  '21 YEARS': { years: 21 },
  '21 YRS': { years: 21 },
  '22 YEARS': { years: 22 },
  '22 YRS': { years: 22 },
  '22 YRS (9 YRS RARO)': { years: 22 },
  '23': { years: 23 },
  '23 YEARS': { years: 23 },
  '23 YRS': { years: 23 },
  '23.': { years: 23 },
  '24 YRS': { years: 24 },
  '25': { years: 25 },
  '25 YEARS': { years: 25 },
  '25 YRS': { years: 25 },
  'OVER 25 YRS': { years: 25 },
  '26': { years: 26 },
  '26 YEARS': { years: 26 },
  '26 YRS': { years: 26 },
  '27': { years: 27 },
  '27 YEARS': { years: 27 },
  '27 YRS': { years: 27 },
  'ABOUT 27 YRS': { years: 27 },
  '28 YEARS': { years: 28 },
  '28 YRS': { years: 28 },
  '29 YEARS': { years: 29 },
  '29 YRS': { years: 29 },

  // Years - 30-39
  '30': { years: 30 },
  '30 YEARS': { years: 30 },
  '30 YRS': { years: 30 },
  '30+ YRS': { years: 30 },
  '30YEARS': { years: 30 },
  '30YRS': { years: 30 },
  'ABOUT 30 YRS': { years: 30 },
  'OVER 30 YRS': { years: 30 },
  '31': { years: 31 },
  '31 YEARS': { years: 31 },
  '31 YRS': { years: 31 },
  'ABOUT 31 YRS': { years: 31 },
  '32 YEARS': { years: 32 },
  '32 YRS': { years: 32 },
  '32YRS': { years: 32 },
  '33 YRS': { years: 33 },
  '33YRS': { years: 33 },
  '34 YRS': { years: 34 },
  '34YRS': { years: 34 },
  '35': { years: 35 },
  '35 YEARS': { years: 35 },
  '35 YRS': { years: 35 },
  'ABOUT 35 YRS': { years: 35 },
  '36': { years: 36 },
  '36 YRS': { years: 36 },
  '37 YRS': { years: 37 },
  '37YRS': { years: 37 },
  '38 YRS': { years: 38 },
  '39 YEARS': { years: 39 },
  '39 YRS': { years: 39 },

  // Years - 40-49
  '40': { years: 40 },
  '40 YRS': { years: 40 },
  '40YRS': { years: 40 },
  'OVER 40 YEARS': { years: 40 },
  'OVER 40 YRS': { years: 40 },
  '41 YRS': { years: 41 },
  '42 YEARS': { years: 42 },
  '42 YRS': { years: 42 },
  '43 YRS': { years: 43 },
  '43YRS': { years: 43 },
  'ABOUT 43 YRS': { years: 43 },
  '44': { years: 44 },
  '44 YRS': { years: 44 },
  '45 YEARS': { years: 45 },
  '45 YRS': { years: 45 },
  '45YRS': { years: 45 },
  '46 YRS': { years: 46 },
  '46 YRS`': { years: 46 },
  '47 YRS': { years: 47 },
  '48 YRS': { years: 48 },
  '49 YRS': { years: 49 },

  // Years - 50-59
  '50': { years: 50 },
  '50 + YRS': { years: 50 },
  '50 YRS': { years: 50 },
  '50YRS': { years: 50 },
  'ABOUT 50 YRS': { years: 50 },
  'OVER 50 YRS': { years: 50 },
  '51 YRS': { years: 51 },
  '51YRS': { years: 51 },
  'ABOUT 51 YRS': { years: 51 },
  '52 YRS': { years: 52 },
  'ABOUT 52 YRS': { years: 52 },
  '53': { years: 53 },
  '53 YRS': { years: 53 },
  '54': { years: 54 },
  '54 YRS': { years: 54 },
  '54YEARS': { years: 54 },
  '54YRS': { years: 54 },
  '55 YRS': { years: 55 },
  'ABOUT 55 YRS': { years: 55 },
  '56 YRS': { years: 56 },
  'ABOUT 56 YRS': { years: 56 },
  '57 YEARS': { years: 57 },
  '57 YRS': { years: 57 },
  '57 YRS SINCE BIRTH': { sinceBirth: true },
  '57YRS': { years: 57 },
  '58 YRS': { years: 58 },
  '59': { years: 59 },
  '59 YEARS': { years: 59 },
  '59 YRS': { years: 59 },

  // Years - 60-69
  '60': { years: 60 },
  '60 YRS': { years: 60 },
  '60+ YRS': { years: 60 },
  '60YRS': { years: 60 },
  'ABOUT 60 YRS': { years: 60 },
  'OVER 60 YRS': { years: 60 },
  '61 YRS': { years: 61 },
  '62 YRS': { years: 62 },
  '62 YRS 9 MONTHS': { years: 62 },
  '62YRS': { years: 62 },
  '63 YRS': { years: 63 },
  '63YRS': { years: 63 },
  '64 YEARS': { years: 64 },
  '64 YRS': { years: 64 },
  'SIXTY FOUR YEARS': { years: 64 },
  '65': { years: 65 },
  '65 YRS': { years: 65 },
  'ABOUT 65 YRS': { years: 65 },
  '66 YRS': { years: 66 },
  '66 YRS APPROX': { years: 66 },
  '67': { years: 67 },
  '67 YRS': { years: 67 },
  '68 YEARS': { years: 68 },
  '68 YRS': { years: 68 },
  '68YEARS': { years: 68 },
  '68YRS': { years: 68 },
  '69 YEARS': { years: 69 },
  '69 YRS': { years: 69 },

  // Years - 70-79
  '70': { years: 70 },
  '70 + YRS': { years: 70 },
  '70 YRS': { years: 70 },
  '70+ YRS': { years: 70 },
  'OVER 70': { years: 70 },
  '71 YRS': { years: 71 },
  '71 YRS SINCE BIRTH': { sinceBirth: true },
  '72': { years: 72 },
  '72 YRS': { years: 72 },
  '73': { years: 73 },
  '73 YEARS': { years: 73 },
  '73 YRS': { years: 73 },
  '73YRS': { years: 73 },
  '74 YRS': { years: 74 },
  '75 YRS': { years: 75 },
  '75 years': { years: 75 },
  '76': { years: 76 },
  '76 YRS': { years: 76 },
  '76YEARS': { years: 76 },
  'SEVENTY SIX YRS': { years: 76 },
  '77 YEARS': { years: 77 },
  '77 YRS': { years: 77 },
  '78': { years: 78 },
  '78 YEARS': { years: 78 },
  '78 YRS': { years: 78 },
  '79 YEARS': { years: 79 },
  '79 YRS': { years: 79 },

  // Years - 80-89
  '80': { years: 80 },
  '80 YEARS': { years: 80 },
  '80 YRS': { years: 80 },
  '80+ YRS': { years: 80 },
  '80YRS': { years: 80 },
  'OVER 80 YRS': { years: 80 },
  '81 YRS': { years: 81 },
  '82 YRS': { years: 82 },
  '83 YRS': { years: 83 },
  '84': { years: 84 },
  '84 YRS': { years: 84 },
  '84 yrs': { years: 84 },
  '84YEARS': { years: 84 },
  '85 YRS': { years: 85 },
  '86 YRS': { years: 86 },
  '87 YEARS': { years: 87 },
  '87 YRS': { years: 87 },
  '88': { years: 88 },
  'OVER 88 YRS': { years: 88 },
  '89 YRS': { years: 89 },

  // Years - 90+
  '90 YRS': { years: 90 },
  '94 YRS': { years: 94 },
  '96 YRS': { years: 96 },
  'APPROX 102 YRS': { years: 102 },

  // Since birth variations
  'SINCE BIRTH': { sinceBirth: true },
  'SINCE  BIRTH': { sinceBirth: true },
  'SINCE BIIRTH': { sinceBirth: true },
  'SINCE BIRHT': { sinceBirth: true },
  'SINCE BIRTH (8 DAYS)': { sinceBirth: true },
  'SINCE BIRTH 18 YRS': { sinceBirth: true },
  'SINCE BIRTH 76 YRS': { sinceBirth: true },
  'SINCE BORN': { sinceBirth: true },
  'SINCE BORN 82 YRS': { sinceBirth: true },
  'SINCE BRITH': { sinceBirth: true },
  'SINCE BRITHS': { sinceBirth: true },
  'SINCE CBIRTH': { sinceBirth: true },
  SINCEBIRTH: { sinceBirth: true },
  'SINCED BIRTH': { sinceBirth: true },
  'SICNE BIRTH': { sinceBirth: true },
  'SIINCE BIRTH': { sinceBirth: true },
  'SINC BIRTH': { sinceBirth: true },
  'SINC EBIRTH': { sinceBirth: true },
  'SINE BIRTH': { sinceBirth: true },
  'SINXCE BIRTH': { sinceBirth: true },
  'Since Birth': { sinceBirth: true },

  // Since childhood/baby
  'SINCE A BABY': { sinceBirth: true },
  'SINCE A CHILD': { sinceBirth: true },
  'SINCE CHILDHOOD': { sinceBirth: true },
  INFANT: { sinceBirth: true },

  // Since X years old (functions that calculate based on age)
  'SINCE 3 YRS OLD': (age: number | null) => ({ years: age ? age - 3 : 0 }),

  // Lifetime variations
  'ALL HER LIFE': { sinceBirth: true },
  'ALL HIS FILE': { sinceBirth: true }, // Typo for "life"
  'ALL HIS LIFE': { sinceBirth: true },
  'ALL LIFE': { sinceBirth: true },
  ALWAYS: { sinceBirth: true },
  'DURATION OF LIFE': { sinceBirth: true },
  LIFE: { sinceBirth: true },
  'LIFE TIME': { sinceBirth: true },
  LIFETIME: { sinceBirth: true },
  'LIFETIME 75YRS': { sinceBirth: true },
  'MOST OF HER LIFE': { sinceBirth: true },
  'MOST OF HIS LIFE': { sinceBirth: true },
  PERMANENT: { sinceBirth: true },

  // Vague/unclear time periods
  'FOR SOME YEARS': { years: 1 },
  'FOR SOME YRS': { years: 1 },
  'FOR YRS': { years: 1 },
  SEVERAL: { years: 1 },
  'SEVERAL YEARS': { years: 1 },
  'SEVERAL YRS': { years: 1 },
  'SOME YEARS': { years: 1 },
  'SOME YRS': { years: 1 },
  YEARS: { years: 1 },
  YRS: { years: 1 },
  Years: { years: 1 },
  'ABOUT YRS': { years: 1 },

  // Location names (appear to be data entry errors for country of residence)
  'C.I.C.C.': { years: 0 }, // Cook Islands Christian Church
  MANIHIKI: { years: 0 }, // Island name
  OIRETUMU: { years: 0 }, // Location name
  RAROTONGA: { years: 0 }, // Island name
  TITIKAVEKA: { years: 0 }, // Village name
  'LIVING IN NEW ZEALAN': { years: 0 },

  // Date entries (data entry errors)
  'SINCE 1946': (_, date: string) => ({ years: dateDiff(date, 1946) }),
  'SINCE 1957': (_, date: string) => ({ years: dateDiff(date, 1957) }),
  'SINCE 2001': (_, date: string) => ({ years: dateDiff(date, 2001) }),
  'SINCE 2010': (_, date: string) => ({ years: dateDiff(date, 2010) }),
  'SINCE 8/9/1971': (_, date: string) => ({ years: dateDiff(date, 1971) }),
  'SINCE DECEMBER 2019': (_, date: string) => ({ years: dateDiff(date, 2019) }),

  // Misclassified entries
  SINCE: { years: 0 },
  'SINCE CITY': { years: 0 },
  'SINCE DEATH': { years: 0 },
  'SINGLE BIRTH': { years: 0 },
  'STILL BIRTH': { years: 0 },
  'STILL BORN': { years: 0 },
  STILLBIRTH: { years: 0 },
}

function dateDiff(date: string, targetYear: number): number {
  const year = date.substring(0, 4)
  const intYear = parseInt(year, 10)

  return isNaN(intYear) ? 0 : targetYear - intYear
}

export function resolveLengthInCis(
  key: string,
  age: number | null,
  date: string,
): { years?: number; sinceBirth?: boolean } {
  const value = lengthInCis[key]
  if (!value) return { years: 0 }

  if (typeof value === 'function') {
    return value(age, date) as { years: number }
  }

  return value
}
